# Generated by Django 4.2.8 on 2023-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='story_header',
            field=models.CharField(max_length=135),
        ),
    ]
