# Generated by Django 4.2.8 on 2023-12-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_story_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='story_contnet',
            new_name='story_contnet_arabic',
        ),
        migrations.RemoveField(
            model_name='content',
            name='story_header',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='contact_no_arabic',
            field=models.CharField(default='test', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='email_arabic',
            field=models.EmailField(default='test', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='location_arabic',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_arabic',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='story_contnet_english',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='story_header_arabic',
            field=models.CharField(default='test', max_length=625),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='story_header_english',
            field=models.CharField(default='test', max_length=625),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_arabic',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='title_arabic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
