# Generated by Django 4.2.8 on 2023-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_bannercontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='code',
        ),
        migrations.AddField(
            model_name='contact_us',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
