# Generated by Django 4.2 on 2024-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_name_english', models.CharField(max_length=50)),
                ('navigation_name_english_link', models.CharField(max_length=750)),
                ('navigation_name_arabic', models.CharField(max_length=50)),
                ('navigation_name_arabic_link', models.CharField(max_length=750)),
            ],
        ),
    ]
